### PR TITLE
Fix Sign-in for SoundCloud account

### LINKED ISSUE #28: After signing into SoundCloud the authentication window persists
Hey 👋🏼 

Thanks for building this app!

I'm not sure if I'm doing something wrong (which could totally be the case here) but after signing into SoundCloud in the WebView it just redirects me back to the regular website inside the WebView. I suppose it's meant to show the native version of the app instead.

Is there something I'm overseeing?

I'm assuming that the redirect back to the Native App somehow along the way doesn't work.

https://github.com/lbrndnr/nuage-macos/assets/6411752/2beb6892-5bc5-411e-94f8-8852744ed182

FWIW this was happening on 0.0.4 and is also happening on the new 0.0.5 version.

Let me know if I can provide any more insights which could help to pinpoint the issue.

### PR DESCRIPTION
**Pull request by marcoroth**
Apparently, when signing into SoundCloud via https://soundcloud.com/signin it's not re-requesting the page from the server again, which means the cookies don't get sent from the server-side since the login logic is all handled client-side. The user gets is signed in the WebView, but doesn't have the needed `oauth_token` cookie Nuage is looking for.

When reloading the page it properly re-requests the page from the server-side which then also properly sets all the cookies. But of course, manually reloading the page is not very user-friendly.

Therefore this pull request updates the WebView logic to listen for changes to the `WebView.url` property and scans the cookies again in such instances. I assume it didn't work before because it ran the cookie-check too early in the chain of events, while the "after-sign-in page" wasn't fully loaded yet.

With this observer it receives the needed `oauth_token` cookie in-time and can continue as intended.

Resolves #28

### CODE REVIEW

File: Nuage/Views/WebView.swift [hunk 1]
```diff
@@ -83,4 +76,30 @@ class WebViewCoordinator: NSObject, WKNavigationDelegate, WKUIDelegate {
         webView.window?.close()
     }
     
+    override func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?) {
+        if keyPath == "URL" {
+            let webView = object! as! WKWebView
+          
+            if (webView != nil) {
```
Comment (marcoroth) [inline Nuage/Views/WebView.swift:83]: I'm sure there is some better way here so we don't have to force-unwrap the value and cast it from `Any` to `WKWebView`

Comment (lbrndnr) [reply Nuage/Views/WebView.swift]: You can do 
```
if let webView = object as? WKWebView {

}
```

**Comment by lbrndnr** [comment]
Thanks for fixing it! This looks really good :)

File: Nuage/Views/WebView.swift (hunk 1 above)
Comment (marcoroth) [reply Nuage/Views/WebView.swift]: This compiles:
```swift
if let webView = object as? WKWebView {
  self.scanCookiesForAccessToken(webView: webView)
}
```
but it's crashing the app. It's crashing in the same why as it did before I added the `if (webView != nil)` check around `self.scanCookiesForAccessToken`:
```swift
let webView = object! as! WKWebView
self.scanCookiesForAccessToken(webView: webView)
```

I only get a `Thread 1: EXC_BAD_ACCESS (code=1, address=0x3294db7d48d0)` which leads me to believe that some of the typing/casting is going wrong.

Comment (marcoroth) [reply Nuage/Views/WebView.swift]: Okay, seems like using `Combine` is more reliable and works better
